//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLPrac3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Load()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int bol_num { get; set; }
        public Nullable<byte> load_status { get; set; }
        public string pro_num { get; set; }
        public string quote_num { get; set; }
        public string ref_num { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> pieces { get; set; }
        public string commodity { get; set; }
        public Nullable<double> mileage { get; set; }
        public Nullable<decimal> carrier_rate { get; set; }
        public Nullable<decimal> customer_rate { get; set; }
        public Nullable<System.DateTime> pick_date { get; set; }
        public Nullable<System.TimeSpan> pick_time { get; set; }
        public Nullable<int> pick_address_id { get; set; }
        public Nullable<System.DateTime> drop_appointment { get; set; }
        public Nullable<System.TimeSpan> drop_time { get; set; }
        public Nullable<int> drop_address_id { get; set; }
        public Nullable<System.TimeSpan> eta_time { get; set; }
        public Nullable<System.TimeSpan> last_updated_time { get; set; }
        public Nullable<int> carrier_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> dispatch_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> broker_id { get; set; }
        public Nullable<int> account_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Broker Broker { get; set; }
        public virtual Carrier Carrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Dispatcher Dispatcher { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
